/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpellLangScopeProvider extends DelegatingScopeProvider {
}
