/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.mdd.spelllang.ui.internal.SpelllangActivator;

public class SpellLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpelllangActivator.getInstance().getInjector("uk.ac.kcl.inf.mdd.SpellLang");
	}

}
