/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SpellLangRuntimeModule extends AbstractSpellLangRuntimeModule {
}
