/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SpellLangValidator extends AbstractSpellLangValidator {
}
