/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.mdd.parser.antlr.internal.InternalSpellLangParser;
import uk.ac.kcl.inf.mdd.services.SpellLangGrammarAccess;

public class SpellLangParser extends AbstractAntlrParser {

	@Inject
	private SpellLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSpellLangParser createParser(XtextTokenStream stream) {
		return new InternalSpellLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SpellLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SpellLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
