/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.mdd.spellLang.SimpleSpell;
import uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Spell</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleSpellImpl extends SpellExpressionImpl implements SimpleSpell
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleSpellImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpellLangPackage.Literals.SIMPLE_SPELL;
  }

} //SimpleSpellImpl
