/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.mdd.spellLang.SpellDefinition;
import uk.ac.kcl.inf.mdd.spellLang.SpellExpression;
import uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Spell Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.spellLang.impl.SpellDefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.spellLang.impl.SpellDefinitionImpl#getSpellCode <em>Spell Code</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SpellDefinitionImpl extends MinimalEObjectImpl.Container implements SpellDefinition
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSpellCode() <em>Spell Code</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpellCode()
   * @generated
   * @ordered
   */
  protected SpellExpression spellCode;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SpellDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpellLangPackage.Literals.SPELL_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SpellLangPackage.SPELL_DEFINITION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SpellExpression getSpellCode()
  {
    return spellCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSpellCode(SpellExpression newSpellCode, NotificationChain msgs)
  {
    SpellExpression oldSpellCode = spellCode;
    spellCode = newSpellCode;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SpellLangPackage.SPELL_DEFINITION__SPELL_CODE, oldSpellCode, newSpellCode);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpellCode(SpellExpression newSpellCode)
  {
    if (newSpellCode != spellCode)
    {
      NotificationChain msgs = null;
      if (spellCode != null)
        msgs = ((InternalEObject)spellCode).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SpellLangPackage.SPELL_DEFINITION__SPELL_CODE, null, msgs);
      if (newSpellCode != null)
        msgs = ((InternalEObject)newSpellCode).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SpellLangPackage.SPELL_DEFINITION__SPELL_CODE, null, msgs);
      msgs = basicSetSpellCode(newSpellCode, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SpellLangPackage.SPELL_DEFINITION__SPELL_CODE, newSpellCode, newSpellCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SpellLangPackage.SPELL_DEFINITION__SPELL_CODE:
        return basicSetSpellCode(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SpellLangPackage.SPELL_DEFINITION__NAME:
        return getName();
      case SpellLangPackage.SPELL_DEFINITION__SPELL_CODE:
        return getSpellCode();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SpellLangPackage.SPELL_DEFINITION__NAME:
        setName((String)newValue);
        return;
      case SpellLangPackage.SPELL_DEFINITION__SPELL_CODE:
        setSpellCode((SpellExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SpellLangPackage.SPELL_DEFINITION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SpellLangPackage.SPELL_DEFINITION__SPELL_CODE:
        setSpellCode((SpellExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SpellLangPackage.SPELL_DEFINITION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SpellLangPackage.SPELL_DEFINITION__SPELL_CODE:
        return spellCode != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //SpellDefinitionImpl
