/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SpellLangUiModule extends AbstractSpellLangUiModule {
  public SpellLangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
