/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Spell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.spellLang.ComplexSpell#getStart <em>Start</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.spellLang.ComplexSpell#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getComplexSpell()
 * @model
 * @generated
 */
public interface ComplexSpell extends SpellExpression
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(SpellExpression)
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getComplexSpell_Start()
   * @model containment="true"
   * @generated
   */
  SpellExpression getStart();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.spellLang.ComplexSpell#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(SpellExpression value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.mdd.spellLang.SimpleSpell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference list.
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getComplexSpell_Next()
   * @model containment="true"
   * @generated
   */
  EList<SimpleSpell> getNext();

} // ComplexSpell
