/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.spellLang.Move#getMovement <em>Movement</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getMove()
 * @model
 * @generated
 */
public interface Move extends SimpleSpell
{
  /**
   * Returns the value of the '<em><b>Movement</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.mdd.spellLang.Movement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Movement</em>' attribute.
   * @see uk.ac.kcl.inf.mdd.spellLang.Movement
   * @see #setMovement(Movement)
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getMove_Movement()
   * @model
   * @generated
   */
  Movement getMovement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.spellLang.Move#getMovement <em>Movement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Movement</em>' attribute.
   * @see uk.ac.kcl.inf.mdd.spellLang.Movement
   * @see #getMovement()
   * @generated
   */
  void setMovement(Movement value);

} // Move
