/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Say</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.spellLang.Say#getWord <em>Word</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getSay()
 * @model
 * @generated
 */
public interface Say extends SimpleSpell
{
  /**
   * Returns the value of the '<em><b>Word</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Word</em>' attribute.
   * @see #setWord(String)
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getSay_Word()
   * @model
   * @generated
   */
  String getWord();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.spellLang.Say#getWord <em>Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Word</em>' attribute.
   * @see #getWord()
   * @generated
   */
  void setWord(String value);

} // Say
