/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Spell</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getSimpleSpell()
 * @model
 * @generated
 */
public interface SimpleSpell extends SpellExpression
{
} // SimpleSpell
