/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Spell Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.mdd.spellLang.SpellDefinition#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.mdd.spellLang.SpellDefinition#getSpellCode <em>Spell Code</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getSpellDefinition()
 * @model
 * @generated
 */
public interface SpellDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getSpellDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.spellLang.SpellDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Spell Code</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spell Code</em>' containment reference.
   * @see #setSpellCode(SpellExpression)
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage#getSpellDefinition_SpellCode()
   * @model containment="true"
   * @generated
   */
  SpellExpression getSpellCode();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.mdd.spellLang.SpellDefinition#getSpellCode <em>Spell Code</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spell Code</em>' containment reference.
   * @see #getSpellCode()
   * @generated
   */
  void setSpellCode(SpellExpression value);

} // SpellDefinition
