/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage
 * @generated
 */
public interface SpellLangFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SpellLangFactory eINSTANCE = uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Spell Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Spell Definition</em>'.
   * @generated
   */
  SpellDefinition createSpellDefinition();

  /**
   * Returns a new object of class '<em>Spell Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Spell Expression</em>'.
   * @generated
   */
  SpellExpression createSpellExpression();

  /**
   * Returns a new object of class '<em>Simple Spell</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Spell</em>'.
   * @generated
   */
  SimpleSpell createSimpleSpell();

  /**
   * Returns a new object of class '<em>Say</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Say</em>'.
   * @generated
   */
  Say createSay();

  /**
   * Returns a new object of class '<em>Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move</em>'.
   * @generated
   */
  Move createMove();

  /**
   * Returns a new object of class '<em>Spell Invocation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Spell Invocation</em>'.
   * @generated
   */
  SpellInvocation createSpellInvocation();

  /**
   * Returns a new object of class '<em>Complex Spell</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Complex Spell</em>'.
   * @generated
   */
  ComplexSpell createComplexSpell();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SpellLangPackage getSpellLangPackage();

} //SpellLangFactory
