/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.spellLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.mdd.spellLang.SpellLangFactory
 * @model kind="package"
 * @generated
 */
public interface SpellLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "spellLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/mdd/SpellLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "spellLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SpellLangPackage eINSTANCE = uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.ModelImpl
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Spells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SPELLS = 0;

  /**
   * The feature id for the '<em><b>Session</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SESSION = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SpellDefinitionImpl <em>Spell Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellDefinitionImpl
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSpellDefinition()
   * @generated
   */
  int SPELL_DEFINITION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Spell Code</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL_DEFINITION__SPELL_CODE = 1;

  /**
   * The number of structural features of the '<em>Spell Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL_DEFINITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SpellExpressionImpl <em>Spell Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellExpressionImpl
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSpellExpression()
   * @generated
   */
  int SPELL_EXPRESSION = 2;

  /**
   * The number of structural features of the '<em>Spell Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SimpleSpellImpl <em>Simple Spell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SimpleSpellImpl
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSimpleSpell()
   * @generated
   */
  int SIMPLE_SPELL = 3;

  /**
   * The number of structural features of the '<em>Simple Spell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_SPELL_FEATURE_COUNT = SPELL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SayImpl <em>Say</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SayImpl
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSay()
   * @generated
   */
  int SAY = 4;

  /**
   * The feature id for the '<em><b>Word</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAY__WORD = SIMPLE_SPELL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Say</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAY_FEATURE_COUNT = SIMPLE_SPELL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.MoveImpl
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getMove()
   * @generated
   */
  int MOVE = 5;

  /**
   * The feature id for the '<em><b>Movement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__MOVEMENT = SIMPLE_SPELL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = SIMPLE_SPELL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SpellInvocationImpl <em>Spell Invocation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellInvocationImpl
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSpellInvocation()
   * @generated
   */
  int SPELL_INVOCATION = 6;

  /**
   * The feature id for the '<em><b>Spell</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL_INVOCATION__SPELL = 0;

  /**
   * The number of structural features of the '<em>Spell Invocation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL_INVOCATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.ComplexSpellImpl <em>Complex Spell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.ComplexSpellImpl
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getComplexSpell()
   * @generated
   */
  int COMPLEX_SPELL = 7;

  /**
   * The feature id for the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_SPELL__START = SPELL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_SPELL__NEXT = SPELL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Complex Spell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_SPELL_FEATURE_COUNT = SPELL_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.mdd.spellLang.Movement <em>Movement</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.mdd.spellLang.Movement
   * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getMovement()
   * @generated
   */
  int MOVEMENT = 8;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdd.spellLang.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdd.spellLang.Model#getSpells <em>Spells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Spells</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.Model#getSpells()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Spells();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdd.spellLang.Model#getSession <em>Session</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Session</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.Model#getSession()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Session();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdd.spellLang.SpellDefinition <em>Spell Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Spell Definition</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellDefinition
   * @generated
   */
  EClass getSpellDefinition();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdd.spellLang.SpellDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellDefinition#getName()
   * @see #getSpellDefinition()
   * @generated
   */
  EAttribute getSpellDefinition_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mdd.spellLang.SpellDefinition#getSpellCode <em>Spell Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Spell Code</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellDefinition#getSpellCode()
   * @see #getSpellDefinition()
   * @generated
   */
  EReference getSpellDefinition_SpellCode();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdd.spellLang.SpellExpression <em>Spell Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Spell Expression</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellExpression
   * @generated
   */
  EClass getSpellExpression();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdd.spellLang.SimpleSpell <em>Simple Spell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Spell</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.SimpleSpell
   * @generated
   */
  EClass getSimpleSpell();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdd.spellLang.Say <em>Say</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Say</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.Say
   * @generated
   */
  EClass getSay();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdd.spellLang.Say#getWord <em>Word</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Word</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.Say#getWord()
   * @see #getSay()
   * @generated
   */
  EAttribute getSay_Word();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdd.spellLang.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.mdd.spellLang.Move#getMovement <em>Movement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Movement</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.Move#getMovement()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Movement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdd.spellLang.SpellInvocation <em>Spell Invocation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Spell Invocation</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellInvocation
   * @generated
   */
  EClass getSpellInvocation();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.mdd.spellLang.SpellInvocation#getSpell <em>Spell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Spell</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.SpellInvocation#getSpell()
   * @see #getSpellInvocation()
   * @generated
   */
  EReference getSpellInvocation_Spell();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.mdd.spellLang.ComplexSpell <em>Complex Spell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Spell</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.ComplexSpell
   * @generated
   */
  EClass getComplexSpell();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.mdd.spellLang.ComplexSpell#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Start</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.ComplexSpell#getStart()
   * @see #getComplexSpell()
   * @generated
   */
  EReference getComplexSpell_Start();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.mdd.spellLang.ComplexSpell#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Next</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.ComplexSpell#getNext()
   * @see #getComplexSpell()
   * @generated
   */
  EReference getComplexSpell_Next();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.mdd.spellLang.Movement <em>Movement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Movement</em>'.
   * @see uk.ac.kcl.inf.mdd.spellLang.Movement
   * @generated
   */
  EEnum getMovement();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SpellLangFactory getSpellLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.ModelImpl
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Spells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SPELLS = eINSTANCE.getModel_Spells();

    /**
     * The meta object literal for the '<em><b>Session</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SESSION = eINSTANCE.getModel_Session();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SpellDefinitionImpl <em>Spell Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellDefinitionImpl
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSpellDefinition()
     * @generated
     */
    EClass SPELL_DEFINITION = eINSTANCE.getSpellDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPELL_DEFINITION__NAME = eINSTANCE.getSpellDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Spell Code</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPELL_DEFINITION__SPELL_CODE = eINSTANCE.getSpellDefinition_SpellCode();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SpellExpressionImpl <em>Spell Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellExpressionImpl
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSpellExpression()
     * @generated
     */
    EClass SPELL_EXPRESSION = eINSTANCE.getSpellExpression();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SimpleSpellImpl <em>Simple Spell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SimpleSpellImpl
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSimpleSpell()
     * @generated
     */
    EClass SIMPLE_SPELL = eINSTANCE.getSimpleSpell();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SayImpl <em>Say</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SayImpl
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSay()
     * @generated
     */
    EClass SAY = eINSTANCE.getSay();

    /**
     * The meta object literal for the '<em><b>Word</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SAY__WORD = eINSTANCE.getSay_Word();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.MoveImpl
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>Movement</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__MOVEMENT = eINSTANCE.getMove_Movement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.SpellInvocationImpl <em>Spell Invocation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellInvocationImpl
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getSpellInvocation()
     * @generated
     */
    EClass SPELL_INVOCATION = eINSTANCE.getSpellInvocation();

    /**
     * The meta object literal for the '<em><b>Spell</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPELL_INVOCATION__SPELL = eINSTANCE.getSpellInvocation_Spell();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.impl.ComplexSpellImpl <em>Complex Spell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.ComplexSpellImpl
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getComplexSpell()
     * @generated
     */
    EClass COMPLEX_SPELL = eINSTANCE.getComplexSpell();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_SPELL__START = eINSTANCE.getComplexSpell_Start();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_SPELL__NEXT = eINSTANCE.getComplexSpell_Next();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.mdd.spellLang.Movement <em>Movement</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.mdd.spellLang.Movement
     * @see uk.ac.kcl.inf.mdd.spellLang.impl.SpellLangPackageImpl#getMovement()
     * @generated
     */
    EEnum MOVEMENT = eINSTANCE.getMovement();

  }

} //SpellLangPackage
