/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSpellLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uk.ac.kcl.inf.mdd.spellLang.SpellLangPackage.eINSTANCE);
		return result;
	}
}
