/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.mdd.spelllang.ui.internal.SpelllangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpellLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SpelllangActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SpelllangActivator activator = SpelllangActivator.getInstance();
		return activator != null ? activator.getInjector(SpelllangActivator.UK_AC_KCL_INF_MDD_SPELLLANG) : null;
	}

}
