/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SpellLangIdeModule extends AbstractSpellLangIdeModule {
}
